//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CategoryItem_Task.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {
        public int ItemID { get; set; }
        [Required]
        public string Name { get; set; }
        public Nullable<int> Units { get; set; }
        [Required]
        public Nullable<double> PricePerUnit { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> CatergoryID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
